server:
  port: 8765
spring:
  application:
    name: zzz
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html


eureka:
  client:
    service-url:
      defaultZone: http://10.10.11.94:8761/eureka/
feign:
  hystrix:
    enabled: true
